services:
  montana-trackmania-bot:
    build: .
    container_name: montana-trackmania-bot
    restart: unless-stopped
    
    # Environment variables (create a .env file or use environment section)
    env_file:
      - .env
    
    # Alternative: specify environment variables directly
    # environment:
    #   - DISCORD_TOKEN=your_discord_token_here
    #   - UBI_USERNAME=your_ubisoft_username
    #   - UBI_PASSWORD=your_ubisoft_password
    
    # Mount cache directory as volume for persistence
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs  # Optional: for log files
    
    # DNS configuration to avoid DNS caching issues
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 208.67.222.222
    
    # Health check to detect DNS/connectivity issues
    healthcheck:
      test: ["CMD", "/app/health-check.sh"]
      interval: 2h          # Check every 2 hours
      timeout: 30s
      retries: 3
      start_period: 30s
    
    # Resource limits for Raspberry Pi 5
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Optional: network configuration
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
